### ISSUE TITLE
TODO - Mar 13

### ISSUE THREAD

**Issue by yechukim** [yechukim/animal-check#1]
- [x] BMI 부분 공통 - 사람, 강아지, 고양이
- [x] 강아지랑 고양이 화면에 강아지 고양이 이미지들 뿌리기..
- [x]  클릭시 화면에  귀여운 이모지 sprinkle ?
